name: Update RSS

on:
  schedule:
    - cron: '0 22 * * *'  # Runs daily at 22:00 UTC
  workflow_dispatch:      # Enables manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run generate.py script
        run: python generate.py

      - name: Commit and push rss.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
