name: Update RSS

on:
  schedule:
    # Every 10 minutes from 22:00 to 22:59 UTC
    - cron: '*/10 22 * * *'
    # Every 10 minutes from 23:00 to 23:59 UTC
    - cron: '*/10 23 * * *'
    # Once daily at 06:00 UTC
    - cron: '0 6 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install beautifulsoup4 requests
      - run: python generate.py
      - run: |
          git config user.name "rssbot"
          git config user.email "rss@example.com"
          git add rss.xml
          git commit -m "Update RSS"
          git push || true
