name: Update Feeds and Upload Front Pages

on:
  schedule:
    # Update feeds at 21:59, 22:59, 23:59 UK time (UTC+1 = 20:59, 21:59, 22:59 UTC)
    - cron: '59 20 * * *'
    - cron: '59 21 * * *'
    - cron: '59 22 * * *'
    # Upload at 22:04, 23:04, 00:04 UK time (UTC+1 = 21:04, 22:04, 23:04 UTC)
    - cron: '4 21 * * *'
    - cron: '4 22 * * *'
    - cron: '4 23 * * *'
  workflow_dispatch:

jobs:
  update_feeds:
    if: github.event.schedule != null && (github.event.schedule.cron == '59 20 * * *' || github.event.schedule.cron == '59 21 * * *' || github.event.schedule.cron == '59 22 * * *')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies for feed update
        run: pip install requests beautifulsoup4

      - name: Run generate.py script to create feeds
        run: python generate.py

      - name: Commit and push updated feeds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add rss.xml frontpages.json
          git commit -m "Update RSS and JSON feeds" || echo "No changes to commit"
          git push origin main

  upload_frontpages:
    if: github.event.schedule != null && (github.event.schedule.cron == '4 21 * * *' || github.event.schedule.cron == '4 22 * * *' || github.event.schedule.cron == '4 23 * * *')
    runs-on: ubuntu-latest
    needs: update_feeds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies for upload
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Firebase credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > frontpages-fireb-firebase-adminsdk-fbsvc-ebba7340c0.json

      - name: Run upload script
        run: python upload_news_images_create_documents_field_
