name: Update Feeds and Upload Front Pages

on:
  schedule:
    # This will run the scraper/feed generator at 21:59, 22:59, and 23:59 UK time.
    - cron: '59 20,21,22 * * *'
  workflow_dispatch:

jobs:
  # This job scrapes the site and updates the JSON/RSS files.
  update_feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies for feed update
        run: pip install requests beautifulsoup4

      - name: Run generate.py script to create feeds
        run: python generate.py

      - name: Commit and push updated feeds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add rss.xml frontpages.json
          git commit -m "Update RSS and JSON feeds" || echo "No changes to commit"
          git push origin main

  # This job waits for the first job, then uploads to Firebase.
  upload_frontpages:
    runs-on: ubuntu-latest
    needs: update_feeds # This ensures it always runs AFTER update_feeds completes
    env:
      # This line makes your Gemini API Key available to the Python script
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # It gives GitHub Pages time to publish the new JSON file from the previous job.
      - name: Wait for GitHub Pages to deploy
        run: sleep 20s

      - name: Install dependencies for upload
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Firebase credentials
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json

      - name: Validate Firebase credentials JSON format
        run: python -c "import json; json.load(open('service-account.json'))"

      - name: Run upload script
        run: python upload_news_images_create_documents_fields.py