name: Update Feeds and Upload Front Pages

on:
  schedule:
    # Update feeds at 21:59, 22:59, 23:59 UK time (UTC+1 = 20:59, 21:59, 22:59 UTC)
    - cron: '59 20,21,22 * * *'
    # Upload at 22:04, 23:04, 00:04 UK time (UTC+1 = 21:04, 22:04, 23:04 UTC)
    - cron: '4 21,22,23 * * *'
  workflow_dispatch:

jobs:
  update_feeds:
    # This job runs on all schedules — but will exit early unless the minute is 59
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is a feed update time
        run: |
          if [[ "$(date +'%M')" != "59" ]]; then
            echo "Not a feed update time. Exiting."
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies for feed update
        run: pip install requests beautifulsoup4

      - name: Run generate.py script to create feeds
        run: python generate.py

      - name: Commit and push updated feeds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add rss.xml frontpages.json
          git commit -m "Update RSS and JSON feeds" || echo "No changes to commit"
          git push origin main

  upload_frontpages:
    runs-on: ubuntu-latest
    needs: update_feeds
    steps:
      - name: Check if this is an upload time
        run: |
          if [[ "$(date +'%M')" != "04" ]]; then
            echo "Not an upload time. Exiting."
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies for upload
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Firebase credentials
        run: |
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > frontpages-fireb-firebase-adminsdk-fbsvc-ebba7340c0.json

      - name: Validate Firebase credentials JSON format
        run: python -c "import json; json.load(open('frontpages-fireb-firebase-adminsdk-fbsvc-ebba7340c0.json'))"

      - name: Run upload script
        run: python upload_news_images_create_documents_fields.py
